apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: frontend

spec:
  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend

        image: 401045966536.dkr.ecr.ap-south-1.amazonaws.com/frontend-repo:latest

        ports:
        - containerPort: 3000